# Generated by Django 5.0.7 on 2024-09-01 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
            ],
            options={
                'permissions': [('can_view_Book', 'Can view Book'), ('can_create_Book', 'Can create Book'), ('can_edit_Book', 'Can edit Book'), ('can_delete_Book', 'Can delete Book')],
            },
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
