<<<<<<< HEAD
# Generated by Django 5.1 on 2024-09-05 22:08
=======
# Generated by Django 5.1.1 on 2024-09-05 18:00
>>>>>>> 4426c1bee6525b3a7279a2554af64684bd8720bd

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
<<<<<<< HEAD
                ('publication_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField()),
=======
>>>>>>> 4426c1bee6525b3a7279a2554af64684bd8720bd
            ],
        ),
    ]
